name = "OSforGFF"
version = "0.1.0"
defaultTargets = ["OSforGFF"]

[leanOptions]
"pp.unicode.fun" = true

[[lean_lib]]
name = "OSforGFF"

[[lean_lib]]
name = "DependencyExtractor"

[[require]]
name = "Dress"
git = "https://github.com/e-vergo/Dress.git"
rev = "main"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
